#!/bin/bash
CUDA_VISIBLE_DEVICES=$1 python run_qa.py \
  --model_name_or_path  Results/longformer-squadv2-multispeak \
  --train_file /home/arprasad/AllData/Dataset/final-AMI-train.json \
  --validation_file /home/arprasad/AllData/Dataset/final-AMI-dev.json \
  --test_file /home/arprasad/AllData/Dataset/final-AMI-test.json \
  --do_train \
  --do_eval \
  --do_predict \
  --version_2_with_negative \
  --per_device_train_batch_size 5 \
  --save_total_limit 1 \
  --load_best_model_at_end True \
  --evaluation_strategy epoch \
  --logging_strategy epoch \
  --save_strategy epoch \
  --metric_for_best_model eval_f1 \
  --learning_rate 3e-5 \
  --warmup_ratio 0.2 \
  --num_train_epochs 10 \
  --max_seq_length 1536 \
  --doc_stride 128 \
  --max_answer_length 1024 \
  --output_dir Results/finetuned-mod/longformer-silvermultispeak-ft/
